#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace 学生学籍管理系统
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="学生学籍管理系统")]
	public partial class DataClassesDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region 可扩展性方法定义
    partial void OnCreated();
    partial void Insert查询结果存储表(查询结果存储表 instance);
    partial void Update查询结果存储表(查询结果存储表 instance);
    partial void Delete查询结果存储表(查询结果存储表 instance);
    partial void Insert临时用户管理表(临时用户管理表 instance);
    partial void Update临时用户管理表(临时用户管理表 instance);
    partial void Delete临时用户管理表(临时用户管理表 instance);
    partial void Insert学生成绩表(学生成绩表 instance);
    partial void Update学生成绩表(学生成绩表 instance);
    partial void Delete学生成绩表(学生成绩表 instance);
    partial void Insert学生档案表(学生档案表 instance);
    partial void Update学生档案表(学生档案表 instance);
    partial void Delete学生档案表(学生档案表 instance);
    partial void Insert学生信息表(学生信息表 instance);
    partial void Update学生信息表(学生信息表 instance);
    partial void Delete学生信息表(学生信息表 instance);
    partial void Insert用户管理表(用户管理表 instance);
    partial void Update用户管理表(用户管理表 instance);
    partial void Delete用户管理表(用户管理表 instance);
    #endregion
		
		public DataClassesDataContext() : 
				base(global::学生学籍管理系统.Properties.Settings.Default.学生学籍管理系统ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClassesDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<查询结果存储表> 查询结果存储表
		{
			get
			{
				return this.GetTable<查询结果存储表>();
			}
		}
		
		public System.Data.Linq.Table<临时用户管理表> 临时用户管理表
		{
			get
			{
				return this.GetTable<临时用户管理表>();
			}
		}
		
		public System.Data.Linq.Table<学生成绩表> 学生成绩表
		{
			get
			{
				return this.GetTable<学生成绩表>();
			}
		}
		
		public System.Data.Linq.Table<学生档案表> 学生档案表
		{
			get
			{
				return this.GetTable<学生档案表>();
			}
		}
		
		public System.Data.Linq.Table<学生信息表> 学生信息表
		{
			get
			{
				return this.GetTable<学生信息表>();
			}
		}
		
		public System.Data.Linq.Table<用户管理表> 用户管理表
		{
			get
			{
				return this.GetTable<用户管理表>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.查询结果存储表")]
	public partial class 查询结果存储表 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _学号;
		
		private string _专业;
		
		private string _班级;
		
		private string _姓名;
		
		private string _性别;
		
		private string _籍贯;
		
		private string _出生年月;
		
		private string _家庭地址;
		
		private string _联系电话;
		
		private string _政治面貌;
		
		private string _民族;
		
		private string _奖罚情况;
		
		private string _留级情况;
		
		private string _高等数学_上_;
		
		private string _高等数学_下_;
		
		private string _概率论;
		
		private string _线性代数;
		
		private string _C语言程序设计;
		
		private string _离散数学;
		
		private int _序号;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On学号Changing(string value);
    partial void On学号Changed();
    partial void On专业Changing(string value);
    partial void On专业Changed();
    partial void On班级Changing(string value);
    partial void On班级Changed();
    partial void On姓名Changing(string value);
    partial void On姓名Changed();
    partial void On性别Changing(string value);
    partial void On性别Changed();
    partial void On籍贯Changing(string value);
    partial void On籍贯Changed();
    partial void On出生年月Changing(string value);
    partial void On出生年月Changed();
    partial void On家庭地址Changing(string value);
    partial void On家庭地址Changed();
    partial void On联系电话Changing(string value);
    partial void On联系电话Changed();
    partial void On政治面貌Changing(string value);
    partial void On政治面貌Changed();
    partial void On民族Changing(string value);
    partial void On民族Changed();
    partial void On奖罚情况Changing(string value);
    partial void On奖罚情况Changed();
    partial void On留级情况Changing(string value);
    partial void On留级情况Changed();
    partial void On高等数学_上_Changing(string value);
    partial void On高等数学_上_Changed();
    partial void On高等数学_下_Changing(string value);
    partial void On高等数学_下_Changed();
    partial void On概率论Changing(string value);
    partial void On概率论Changed();
    partial void On线性代数Changing(string value);
    partial void On线性代数Changed();
    partial void OnC语言程序设计Changing(string value);
    partial void OnC语言程序设计Changed();
    partial void On离散数学Changing(string value);
    partial void On离散数学Changed();
    partial void On序号Changing(int value);
    partial void On序号Changed();
    #endregion
		
		public 查询结果存储表()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学号", DbType="VarChar(50)")]
		public string 学号
		{
			get
			{
				return this._学号;
			}
			set
			{
				if ((this._学号 != value))
				{
					this.On学号Changing(value);
					this.SendPropertyChanging();
					this._学号 = value;
					this.SendPropertyChanged("学号");
					this.On学号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_专业", DbType="VarChar(50)")]
		public string 专业
		{
			get
			{
				return this._专业;
			}
			set
			{
				if ((this._专业 != value))
				{
					this.On专业Changing(value);
					this.SendPropertyChanging();
					this._专业 = value;
					this.SendPropertyChanged("专业");
					this.On专业Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_班级", DbType="VarChar(50)")]
		public string 班级
		{
			get
			{
				return this._班级;
			}
			set
			{
				if ((this._班级 != value))
				{
					this.On班级Changing(value);
					this.SendPropertyChanging();
					this._班级 = value;
					this.SendPropertyChanged("班级");
					this.On班级Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_姓名", DbType="VarChar(50)")]
		public string 姓名
		{
			get
			{
				return this._姓名;
			}
			set
			{
				if ((this._姓名 != value))
				{
					this.On姓名Changing(value);
					this.SendPropertyChanging();
					this._姓名 = value;
					this.SendPropertyChanged("姓名");
					this.On姓名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_性别", DbType="VarChar(50)")]
		public string 性别
		{
			get
			{
				return this._性别;
			}
			set
			{
				if ((this._性别 != value))
				{
					this.On性别Changing(value);
					this.SendPropertyChanging();
					this._性别 = value;
					this.SendPropertyChanged("性别");
					this.On性别Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_籍贯", DbType="VarChar(50)")]
		public string 籍贯
		{
			get
			{
				return this._籍贯;
			}
			set
			{
				if ((this._籍贯 != value))
				{
					this.On籍贯Changing(value);
					this.SendPropertyChanging();
					this._籍贯 = value;
					this.SendPropertyChanged("籍贯");
					this.On籍贯Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_出生年月", DbType="VarChar(50)")]
		public string 出生年月
		{
			get
			{
				return this._出生年月;
			}
			set
			{
				if ((this._出生年月 != value))
				{
					this.On出生年月Changing(value);
					this.SendPropertyChanging();
					this._出生年月 = value;
					this.SendPropertyChanged("出生年月");
					this.On出生年月Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_家庭地址", DbType="VarChar(50)")]
		public string 家庭地址
		{
			get
			{
				return this._家庭地址;
			}
			set
			{
				if ((this._家庭地址 != value))
				{
					this.On家庭地址Changing(value);
					this.SendPropertyChanging();
					this._家庭地址 = value;
					this.SendPropertyChanged("家庭地址");
					this.On家庭地址Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_联系电话", DbType="VarChar(50)")]
		public string 联系电话
		{
			get
			{
				return this._联系电话;
			}
			set
			{
				if ((this._联系电话 != value))
				{
					this.On联系电话Changing(value);
					this.SendPropertyChanging();
					this._联系电话 = value;
					this.SendPropertyChanged("联系电话");
					this.On联系电话Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_政治面貌", DbType="VarChar(50)")]
		public string 政治面貌
		{
			get
			{
				return this._政治面貌;
			}
			set
			{
				if ((this._政治面貌 != value))
				{
					this.On政治面貌Changing(value);
					this.SendPropertyChanging();
					this._政治面貌 = value;
					this.SendPropertyChanged("政治面貌");
					this.On政治面貌Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_民族", DbType="VarChar(50)")]
		public string 民族
		{
			get
			{
				return this._民族;
			}
			set
			{
				if ((this._民族 != value))
				{
					this.On民族Changing(value);
					this.SendPropertyChanging();
					this._民族 = value;
					this.SendPropertyChanged("民族");
					this.On民族Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_奖罚情况", DbType="VarChar(50)")]
		public string 奖罚情况
		{
			get
			{
				return this._奖罚情况;
			}
			set
			{
				if ((this._奖罚情况 != value))
				{
					this.On奖罚情况Changing(value);
					this.SendPropertyChanging();
					this._奖罚情况 = value;
					this.SendPropertyChanged("奖罚情况");
					this.On奖罚情况Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_留级情况", DbType="VarChar(50)")]
		public string 留级情况
		{
			get
			{
				return this._留级情况;
			}
			set
			{
				if ((this._留级情况 != value))
				{
					this.On留级情况Changing(value);
					this.SendPropertyChanging();
					this._留级情况 = value;
					this.SendPropertyChanged("留级情况");
					this.On留级情况Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[高等数学（上）]", Storage="_高等数学_上_", DbType="VarChar(50)")]
		public string 高等数学_上_
		{
			get
			{
				return this._高等数学_上_;
			}
			set
			{
				if ((this._高等数学_上_ != value))
				{
					this.On高等数学_上_Changing(value);
					this.SendPropertyChanging();
					this._高等数学_上_ = value;
					this.SendPropertyChanged("高等数学_上_");
					this.On高等数学_上_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[高等数学（下）]", Storage="_高等数学_下_", DbType="VarChar(50)")]
		public string 高等数学_下_
		{
			get
			{
				return this._高等数学_下_;
			}
			set
			{
				if ((this._高等数学_下_ != value))
				{
					this.On高等数学_下_Changing(value);
					this.SendPropertyChanging();
					this._高等数学_下_ = value;
					this.SendPropertyChanged("高等数学_下_");
					this.On高等数学_下_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_概率论", DbType="VarChar(50)")]
		public string 概率论
		{
			get
			{
				return this._概率论;
			}
			set
			{
				if ((this._概率论 != value))
				{
					this.On概率论Changing(value);
					this.SendPropertyChanging();
					this._概率论 = value;
					this.SendPropertyChanged("概率论");
					this.On概率论Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_线性代数", DbType="VarChar(50)")]
		public string 线性代数
		{
			get
			{
				return this._线性代数;
			}
			set
			{
				if ((this._线性代数 != value))
				{
					this.On线性代数Changing(value);
					this.SendPropertyChanging();
					this._线性代数 = value;
					this.SendPropertyChanged("线性代数");
					this.On线性代数Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_C语言程序设计", DbType="VarChar(50)")]
		public string C语言程序设计
		{
			get
			{
				return this._C语言程序设计;
			}
			set
			{
				if ((this._C语言程序设计 != value))
				{
					this.OnC语言程序设计Changing(value);
					this.SendPropertyChanging();
					this._C语言程序设计 = value;
					this.SendPropertyChanged("C语言程序设计");
					this.OnC语言程序设计Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_离散数学", DbType="VarChar(50)")]
		public string 离散数学
		{
			get
			{
				return this._离散数学;
			}
			set
			{
				if ((this._离散数学 != value))
				{
					this.On离散数学Changing(value);
					this.SendPropertyChanging();
					this._离散数学 = value;
					this.SendPropertyChanged("离散数学");
					this.On离散数学Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_序号", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int 序号
		{
			get
			{
				return this._序号;
			}
			set
			{
				if ((this._序号 != value))
				{
					this.On序号Changing(value);
					this.SendPropertyChanging();
					this._序号 = value;
					this.SendPropertyChanged("序号");
					this.On序号Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.临时用户管理表")]
	public partial class 临时用户管理表 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _学号;
		
		private string _用户名;
		
		private string _密码;
		
		private int _序号;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On学号Changing(string value);
    partial void On学号Changed();
    partial void On用户名Changing(string value);
    partial void On用户名Changed();
    partial void On密码Changing(string value);
    partial void On密码Changed();
    partial void On序号Changing(int value);
    partial void On序号Changed();
    #endregion
		
		public 临时用户管理表()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学号", DbType="VarChar(50)")]
		public string 学号
		{
			get
			{
				return this._学号;
			}
			set
			{
				if ((this._学号 != value))
				{
					this.On学号Changing(value);
					this.SendPropertyChanging();
					this._学号 = value;
					this.SendPropertyChanged("学号");
					this.On学号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_用户名", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string 用户名
		{
			get
			{
				return this._用户名;
			}
			set
			{
				if ((this._用户名 != value))
				{
					this.On用户名Changing(value);
					this.SendPropertyChanging();
					this._用户名 = value;
					this.SendPropertyChanged("用户名");
					this.On用户名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_密码", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 密码
		{
			get
			{
				return this._密码;
			}
			set
			{
				if ((this._密码 != value))
				{
					this.On密码Changing(value);
					this.SendPropertyChanging();
					this._密码 = value;
					this.SendPropertyChanged("密码");
					this.On密码Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_序号", AutoSync=AutoSync.Always, DbType="Int NOT NULL IDENTITY", IsDbGenerated=true)]
		public int 序号
		{
			get
			{
				return this._序号;
			}
			set
			{
				if ((this._序号 != value))
				{
					this.On序号Changing(value);
					this.SendPropertyChanging();
					this._序号 = value;
					this.SendPropertyChanged("序号");
					this.On序号Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.学生成绩表")]
	public partial class 学生成绩表 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _学号;
		
		private string _专业;
		
		private string _班级;
		
		private string _姓名;
		
		private string _高等数学_上_;
		
		private string _高等数学_下_;
		
		private string _概率论;
		
		private string _线性代数;
		
		private string _c语言程序设计;
		
		private string _离散数学;
		
		private int _序号;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On学号Changing(string value);
    partial void On学号Changed();
    partial void On专业Changing(string value);
    partial void On专业Changed();
    partial void On班级Changing(string value);
    partial void On班级Changed();
    partial void On姓名Changing(string value);
    partial void On姓名Changed();
    partial void On高等数学_上_Changing(string value);
    partial void On高等数学_上_Changed();
    partial void On高等数学_下_Changing(string value);
    partial void On高等数学_下_Changed();
    partial void On概率论Changing(string value);
    partial void On概率论Changed();
    partial void On线性代数Changing(string value);
    partial void On线性代数Changed();
    partial void Onc语言程序设计Changing(string value);
    partial void Onc语言程序设计Changed();
    partial void On离散数学Changing(string value);
    partial void On离散数学Changed();
    partial void On序号Changing(int value);
    partial void On序号Changed();
    #endregion
		
		public 学生成绩表()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学号", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 学号
		{
			get
			{
				return this._学号;
			}
			set
			{
				if ((this._学号 != value))
				{
					this.On学号Changing(value);
					this.SendPropertyChanging();
					this._学号 = value;
					this.SendPropertyChanged("学号");
					this.On学号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_专业", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 专业
		{
			get
			{
				return this._专业;
			}
			set
			{
				if ((this._专业 != value))
				{
					this.On专业Changing(value);
					this.SendPropertyChanging();
					this._专业 = value;
					this.SendPropertyChanged("专业");
					this.On专业Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_班级", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 班级
		{
			get
			{
				return this._班级;
			}
			set
			{
				if ((this._班级 != value))
				{
					this.On班级Changing(value);
					this.SendPropertyChanging();
					this._班级 = value;
					this.SendPropertyChanged("班级");
					this.On班级Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_姓名", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 姓名
		{
			get
			{
				return this._姓名;
			}
			set
			{
				if ((this._姓名 != value))
				{
					this.On姓名Changing(value);
					this.SendPropertyChanging();
					this._姓名 = value;
					this.SendPropertyChanged("姓名");
					this.On姓名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[高等数学（上）]", Storage="_高等数学_上_", DbType="VarChar(50)")]
		public string 高等数学_上_
		{
			get
			{
				return this._高等数学_上_;
			}
			set
			{
				if ((this._高等数学_上_ != value))
				{
					this.On高等数学_上_Changing(value);
					this.SendPropertyChanging();
					this._高等数学_上_ = value;
					this.SendPropertyChanged("高等数学_上_");
					this.On高等数学_上_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Name="[高等数学（下）]", Storage="_高等数学_下_", DbType="VarChar(50)")]
		public string 高等数学_下_
		{
			get
			{
				return this._高等数学_下_;
			}
			set
			{
				if ((this._高等数学_下_ != value))
				{
					this.On高等数学_下_Changing(value);
					this.SendPropertyChanging();
					this._高等数学_下_ = value;
					this.SendPropertyChanged("高等数学_下_");
					this.On高等数学_下_Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_概率论", DbType="VarChar(50)")]
		public string 概率论
		{
			get
			{
				return this._概率论;
			}
			set
			{
				if ((this._概率论 != value))
				{
					this.On概率论Changing(value);
					this.SendPropertyChanging();
					this._概率论 = value;
					this.SendPropertyChanged("概率论");
					this.On概率论Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_线性代数", DbType="VarChar(50)")]
		public string 线性代数
		{
			get
			{
				return this._线性代数;
			}
			set
			{
				if ((this._线性代数 != value))
				{
					this.On线性代数Changing(value);
					this.SendPropertyChanging();
					this._线性代数 = value;
					this.SendPropertyChanged("线性代数");
					this.On线性代数Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_c语言程序设计", DbType="VarChar(50)")]
		public string c语言程序设计
		{
			get
			{
				return this._c语言程序设计;
			}
			set
			{
				if ((this._c语言程序设计 != value))
				{
					this.Onc语言程序设计Changing(value);
					this.SendPropertyChanging();
					this._c语言程序设计 = value;
					this.SendPropertyChanged("c语言程序设计");
					this.Onc语言程序设计Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_离散数学", DbType="VarChar(50)")]
		public string 离散数学
		{
			get
			{
				return this._离散数学;
			}
			set
			{
				if ((this._离散数学 != value))
				{
					this.On离散数学Changing(value);
					this.SendPropertyChanging();
					this._离散数学 = value;
					this.SendPropertyChanged("离散数学");
					this.On离散数学Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_序号", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int 序号
		{
			get
			{
				return this._序号;
			}
			set
			{
				if ((this._序号 != value))
				{
					this.On序号Changing(value);
					this.SendPropertyChanging();
					this._序号 = value;
					this.SendPropertyChanged("序号");
					this.On序号Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.学生档案表")]
	public partial class 学生档案表 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _学号;
		
		private string _专业;
		
		private string _班级;
		
		private string _姓名;
		
		private string _性别;
		
		private string _民族;
		
		private string _籍贯;
		
		private string _家庭住址;
		
		private string _联系电话;
		
		private string _奖罚情况;
		
		private string _留级情况;
		
		private int _序号;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On学号Changing(string value);
    partial void On学号Changed();
    partial void On专业Changing(string value);
    partial void On专业Changed();
    partial void On班级Changing(string value);
    partial void On班级Changed();
    partial void On姓名Changing(string value);
    partial void On姓名Changed();
    partial void On性别Changing(string value);
    partial void On性别Changed();
    partial void On民族Changing(string value);
    partial void On民族Changed();
    partial void On籍贯Changing(string value);
    partial void On籍贯Changed();
    partial void On家庭住址Changing(string value);
    partial void On家庭住址Changed();
    partial void On联系电话Changing(string value);
    partial void On联系电话Changed();
    partial void On奖罚情况Changing(string value);
    partial void On奖罚情况Changed();
    partial void On留级情况Changing(string value);
    partial void On留级情况Changed();
    partial void On序号Changing(int value);
    partial void On序号Changed();
    #endregion
		
		public 学生档案表()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学号", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 学号
		{
			get
			{
				return this._学号;
			}
			set
			{
				if ((this._学号 != value))
				{
					this.On学号Changing(value);
					this.SendPropertyChanging();
					this._学号 = value;
					this.SendPropertyChanged("学号");
					this.On学号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_专业", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 专业
		{
			get
			{
				return this._专业;
			}
			set
			{
				if ((this._专业 != value))
				{
					this.On专业Changing(value);
					this.SendPropertyChanging();
					this._专业 = value;
					this.SendPropertyChanged("专业");
					this.On专业Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_班级", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 班级
		{
			get
			{
				return this._班级;
			}
			set
			{
				if ((this._班级 != value))
				{
					this.On班级Changing(value);
					this.SendPropertyChanging();
					this._班级 = value;
					this.SendPropertyChanged("班级");
					this.On班级Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_姓名", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 姓名
		{
			get
			{
				return this._姓名;
			}
			set
			{
				if ((this._姓名 != value))
				{
					this.On姓名Changing(value);
					this.SendPropertyChanging();
					this._姓名 = value;
					this.SendPropertyChanged("姓名");
					this.On姓名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_性别", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 性别
		{
			get
			{
				return this._性别;
			}
			set
			{
				if ((this._性别 != value))
				{
					this.On性别Changing(value);
					this.SendPropertyChanging();
					this._性别 = value;
					this.SendPropertyChanged("性别");
					this.On性别Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_民族", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 民族
		{
			get
			{
				return this._民族;
			}
			set
			{
				if ((this._民族 != value))
				{
					this.On民族Changing(value);
					this.SendPropertyChanging();
					this._民族 = value;
					this.SendPropertyChanged("民族");
					this.On民族Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_籍贯", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 籍贯
		{
			get
			{
				return this._籍贯;
			}
			set
			{
				if ((this._籍贯 != value))
				{
					this.On籍贯Changing(value);
					this.SendPropertyChanging();
					this._籍贯 = value;
					this.SendPropertyChanged("籍贯");
					this.On籍贯Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_家庭住址", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 家庭住址
		{
			get
			{
				return this._家庭住址;
			}
			set
			{
				if ((this._家庭住址 != value))
				{
					this.On家庭住址Changing(value);
					this.SendPropertyChanging();
					this._家庭住址 = value;
					this.SendPropertyChanged("家庭住址");
					this.On家庭住址Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_联系电话", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 联系电话
		{
			get
			{
				return this._联系电话;
			}
			set
			{
				if ((this._联系电话 != value))
				{
					this.On联系电话Changing(value);
					this.SendPropertyChanging();
					this._联系电话 = value;
					this.SendPropertyChanged("联系电话");
					this.On联系电话Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_奖罚情况", DbType="VarChar(50)")]
		public string 奖罚情况
		{
			get
			{
				return this._奖罚情况;
			}
			set
			{
				if ((this._奖罚情况 != value))
				{
					this.On奖罚情况Changing(value);
					this.SendPropertyChanging();
					this._奖罚情况 = value;
					this.SendPropertyChanged("奖罚情况");
					this.On奖罚情况Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_留级情况", DbType="VarChar(50)")]
		public string 留级情况
		{
			get
			{
				return this._留级情况;
			}
			set
			{
				if ((this._留级情况 != value))
				{
					this.On留级情况Changing(value);
					this.SendPropertyChanging();
					this._留级情况 = value;
					this.SendPropertyChanged("留级情况");
					this.On留级情况Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_序号", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int 序号
		{
			get
			{
				return this._序号;
			}
			set
			{
				if ((this._序号 != value))
				{
					this.On序号Changing(value);
					this.SendPropertyChanging();
					this._序号 = value;
					this.SendPropertyChanged("序号");
					this.On序号Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.学生信息表")]
	public partial class 学生信息表 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _学号;
		
		private string _专业;
		
		private string _班级;
		
		private string _姓名;
		
		private string _性别;
		
		private string _籍贯;
		
		private string _出生年月;
		
		private string _家庭住址;
		
		private string _联系电话;
		
		private string _政治面貌;
		
		private int _序号;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On学号Changing(string value);
    partial void On学号Changed();
    partial void On专业Changing(string value);
    partial void On专业Changed();
    partial void On班级Changing(string value);
    partial void On班级Changed();
    partial void On姓名Changing(string value);
    partial void On姓名Changed();
    partial void On性别Changing(string value);
    partial void On性别Changed();
    partial void On籍贯Changing(string value);
    partial void On籍贯Changed();
    partial void On出生年月Changing(string value);
    partial void On出生年月Changed();
    partial void On家庭住址Changing(string value);
    partial void On家庭住址Changed();
    partial void On联系电话Changing(string value);
    partial void On联系电话Changed();
    partial void On政治面貌Changing(string value);
    partial void On政治面貌Changed();
    partial void On序号Changing(int value);
    partial void On序号Changed();
    #endregion
		
		public 学生信息表()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学号", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 学号
		{
			get
			{
				return this._学号;
			}
			set
			{
				if ((this._学号 != value))
				{
					this.On学号Changing(value);
					this.SendPropertyChanging();
					this._学号 = value;
					this.SendPropertyChanged("学号");
					this.On学号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_专业", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 专业
		{
			get
			{
				return this._专业;
			}
			set
			{
				if ((this._专业 != value))
				{
					this.On专业Changing(value);
					this.SendPropertyChanging();
					this._专业 = value;
					this.SendPropertyChanged("专业");
					this.On专业Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_班级", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 班级
		{
			get
			{
				return this._班级;
			}
			set
			{
				if ((this._班级 != value))
				{
					this.On班级Changing(value);
					this.SendPropertyChanging();
					this._班级 = value;
					this.SendPropertyChanged("班级");
					this.On班级Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_姓名", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 姓名
		{
			get
			{
				return this._姓名;
			}
			set
			{
				if ((this._姓名 != value))
				{
					this.On姓名Changing(value);
					this.SendPropertyChanging();
					this._姓名 = value;
					this.SendPropertyChanged("姓名");
					this.On姓名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_性别", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 性别
		{
			get
			{
				return this._性别;
			}
			set
			{
				if ((this._性别 != value))
				{
					this.On性别Changing(value);
					this.SendPropertyChanging();
					this._性别 = value;
					this.SendPropertyChanged("性别");
					this.On性别Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_籍贯", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 籍贯
		{
			get
			{
				return this._籍贯;
			}
			set
			{
				if ((this._籍贯 != value))
				{
					this.On籍贯Changing(value);
					this.SendPropertyChanging();
					this._籍贯 = value;
					this.SendPropertyChanged("籍贯");
					this.On籍贯Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_出生年月", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 出生年月
		{
			get
			{
				return this._出生年月;
			}
			set
			{
				if ((this._出生年月 != value))
				{
					this.On出生年月Changing(value);
					this.SendPropertyChanging();
					this._出生年月 = value;
					this.SendPropertyChanged("出生年月");
					this.On出生年月Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_家庭住址", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 家庭住址
		{
			get
			{
				return this._家庭住址;
			}
			set
			{
				if ((this._家庭住址 != value))
				{
					this.On家庭住址Changing(value);
					this.SendPropertyChanging();
					this._家庭住址 = value;
					this.SendPropertyChanged("家庭住址");
					this.On家庭住址Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_联系电话", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 联系电话
		{
			get
			{
				return this._联系电话;
			}
			set
			{
				if ((this._联系电话 != value))
				{
					this.On联系电话Changing(value);
					this.SendPropertyChanging();
					this._联系电话 = value;
					this.SendPropertyChanged("联系电话");
					this.On联系电话Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_政治面貌", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 政治面貌
		{
			get
			{
				return this._政治面貌;
			}
			set
			{
				if ((this._政治面貌 != value))
				{
					this.On政治面貌Changing(value);
					this.SendPropertyChanging();
					this._政治面貌 = value;
					this.SendPropertyChanged("政治面貌");
					this.On政治面貌Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_序号", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int 序号
		{
			get
			{
				return this._序号;
			}
			set
			{
				if ((this._序号 != value))
				{
					this.On序号Changing(value);
					this.SendPropertyChanging();
					this._序号 = value;
					this.SendPropertyChanged("序号");
					this.On序号Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.用户管理表")]
	public partial class 用户管理表 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _学号;
		
		private string _用户名;
		
		private string _密码;
		
		private string _是否为教师账户;
		
    #region 可扩展性方法定义
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void On学号Changing(string value);
    partial void On学号Changed();
    partial void On用户名Changing(string value);
    partial void On用户名Changed();
    partial void On密码Changing(string value);
    partial void On密码Changed();
    partial void On是否为教师账户Changing(string value);
    partial void On是否为教师账户Changed();
    #endregion
		
		public 用户管理表()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_学号", DbType="VarChar(50)")]
		public string 学号
		{
			get
			{
				return this._学号;
			}
			set
			{
				if ((this._学号 != value))
				{
					this.On学号Changing(value);
					this.SendPropertyChanging();
					this._学号 = value;
					this.SendPropertyChanged("学号");
					this.On学号Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_用户名", DbType="VarChar(50) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string 用户名
		{
			get
			{
				return this._用户名;
			}
			set
			{
				if ((this._用户名 != value))
				{
					this.On用户名Changing(value);
					this.SendPropertyChanging();
					this._用户名 = value;
					this.SendPropertyChanged("用户名");
					this.On用户名Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_密码", DbType="VarChar(50) NOT NULL", CanBeNull=false)]
		public string 密码
		{
			get
			{
				return this._密码;
			}
			set
			{
				if ((this._密码 != value))
				{
					this.On密码Changing(value);
					this.SendPropertyChanging();
					this._密码 = value;
					this.SendPropertyChanged("密码");
					this.On密码Changed();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_是否为教师账户", DbType="VarChar(50)")]
		public string 是否为教师账户
		{
			get
			{
				return this._是否为教师账户;
			}
			set
			{
				if ((this._是否为教师账户 != value))
				{
					this.On是否为教师账户Changing(value);
					this.SendPropertyChanging();
					this._是否为教师账户 = value;
					this.SendPropertyChanged("是否为教师账户");
					this.On是否为教师账户Changed();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
